name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up TeX Live
      run: |
        sudo apt update
        sudo apt install -y texlive-latex-{base,recommended,extra}

    - name: Compile LaTeX document
      run: |
        make

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fluid-mechanics-book
        path: fluid-mechanics-book.pdf

    - name: Publish PDF to artifacts branch
      run: |
        set -euo pipefail
        PDF=fluid-mechanics-book.pdf
        test -f "$PDF"

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        if [ -d artifacts ]; then
          git worktree prune || true
          rm -rf artifacts
        fi

        if git ls-remote --exit-code origin refs/heads/artifacts >/dev/null 2>&1; then
          git fetch origin artifacts
          # Create (or reset) local branch 'artifacts' tracking remote and attach worktree
          git worktree add -B artifacts artifacts origin/artifacts
        else
          git worktree add -b artifacts artifacts
          find artifacts -mindepth 1 -maxdepth 1 -not -name .git -exec rm -rf {} +
        fi

        if [ -f artifacts/$PDF ] && cmp -s "$PDF" artifacts/$PDF; then
          echo "No PDF changes."
          exit 0
        fi

        cp "$PDF" artifacts/$PDF
        cd artifacts
        git add "$PDF"
        git commit -m "Update $PDF from ${GITHUB_SHA}"
        git push origin artifacts
