name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up TeX Live
      run: |
        sudo apt update
        sudo apt install -y texlive-latex-{base,recommended,extra}

    - name: Compile LaTeX document
      run: |
        make

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fluid-mechanics-notes
        path: notes.pdf

    - name: Publish PDF to artifacts branch
      run: |
        set -euo pipefail
        PDF=notes.pdf
        test -f "$PDF"

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Prepare local artifacts branch (create if missing remotely)
        if git ls-remote --exit-code origin refs/heads/artifacts >/dev/null 2>&1; then
          git fetch origin artifacts:artifacts
        else
          git branch artifacts
        end

        # Use a worktree to avoid altering current checkout
        if [ -d artifacts ]; then
          git worktree remove -f artifacts
        fi
        git worktree add artifacts artifacts

        cp "$PDF" artifacts/
        cd artifacts

        # Decide if commit needed
        if git ls-files --error-unmatch "$PDF" >/dev/null 2>&1; then
          if git diff --quiet -- "$PDF"; then
            echo "No PDF changes."
            exit 0
          fi
        fi

        git add "$PDF"
        git commit -m "Update notes.pdf from ${GITHUB_SHA}"
        git push origin artifacts
