name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up TeX Live
      run: |
        sudo apt update
        sudo apt install -y texlive-latex-{base,recommended,extra}

    - name: Compile LaTeX document
      run: |
        make

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fluid-mechanics-book
        path: fluid-mechanics-book.pdf

    - name: Publish PDF to artifacts branch
      run: |
        set -euo pipefail
        PDF=fluid-mechanics-book.pdf
        test -f "$PDF"

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Clean any stale worktree dir from previous run (defensive)
        if [ -d artifacts ]; then
          git worktree prune || true
          rm -rf artifacts
        fi

        # If remote branch exists, attach worktree to it; else create new branch
        if git ls-remote --exit-code origin refs/heads/artifacts >/dev/null 2>&1; then
          git fetch origin artifacts
          git worktree add artifacts origin/artifacts
        else
          git worktree add -b artifacts artifacts
          # Optional: ensure branch only contains the PDF (remove other files)
          find artifacts -mindepth 1 -maxdepth 1 -not -name .git -exec rm -rf {} +
        fi

        # Change detection BEFORE overwriting
        if [ -f artifacts/fluid-mechanics-book.pdf ] && cmp -s "$PDF" artifacts/fluid-mechanics-book.pdf; then
          echo "No PDF changes."
          exit 0
        fi

        cp "$PDF" artifacts/fluid-mechanics-book.pdf
        cd artifacts
        git add fluid-mechanics-book.pdf
        git commit -m "Update fluid-mechanics-book.pdf from ${GITHUB_SHA}"
        git push origin artifacts
